[phases.setup]
nixPkgs = ["nodejs", "nodejs.pkgs.npm"]

[phases.install]
cmds = ["cd backend && npm ci"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && node server.js"