[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci"

[deploy]
startCommand = "cd backend && node server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"